#!/usr/bin/perl

# Reads from a Rails logfile to be inputted by user (see sample development.log)
# Outputs gets and posts request URLs to files: ps4_output_posts, ps4_output_gets
# Sample run: ./ps4 
# Input: development.log

print "Input Rails log file: ";
chomp($input_log = <STDIN>);

print $input_log;

open INPUT_FILE, $input_log or die "Coudn't open $input_log ($!)";

@posts = ();
@gets = ();

while (defined($line = <INPUT_FILE>)) {

  $post_start = 'Started POST "';
  $get_start = 'Started GET "';
  $end = '"';

  @temp_posts = ($line =~ /$post_start(.*?)$end/g);
  @temp_gets = ($line =~ /$get_start(.*?)$end/g);

  foreach my $temp (@temp_posts) {
    push @posts, $temp
  }

  foreach my $temp (@temp_gets) {
    push @gets, $temp
  }
}

print "See log files at: \n";
print "  [0] ps4_output_posts\n";
print "  [1] ps4_output_gets\n";



open POST_OUTPUT, "> ps4_output_posts";
open GET_OUTPUT, "> ps4_output_gets";

foreach $post (@posts) {
  print POST_OUTPUT "[POST] $post\n";
}

foreach $get (@gets) {
  print GET_OUTPUT "[GET] $get\n";
}

close POST_OUTPUT;
close GET_OUTPUT;

